version: '3'

include:
  - ./ui-service/docker-compose.yml
  - ./job-creation-service/docker-compose.yml
  - ./notification-worker/docker-compose.yml
  - ./job-repository-service/docker-compose.yml

services:
  queue:
    image: "rabbitmq:3.11"
    container_name: queue
    hostname: backend-queue
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=Pass123
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./definitions.json:/etc/rabbitmq/definitions.json:ro

  reverseproxy:
    image: nginx:latest
    container_name: reverseproxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - ui-service
      - job-repository-service
    restart: on-failure