version: '3'

services:
  ui-service:
    image: node:18.16.0 
    container_name: react-app
    hostname: ui-service
    working_dir: /app
    env_file:
    - ./.env
    volumes:
      - ./:/app
    command: sh -c "npm install && npm start"