version: '3'

services:
  notification-worker:
    image: node:18.16.0 
    container_name: notification-worker
    working_dir: /app
    env_file:
    - ./.env
    ports:
      - "3006:3000" 
    volumes:
      - ./:/app
    command: sh -c "npm install && npm run start:dev"
    depends_on:
      - queue