
export default () => ({
    APP:{
        PASSWORD_SALT_ROUNDS: process.env.BCRYPT_HASH_ROUNDS,
        EXPIRES_IN_TIME_FOR_ACCESS_TOKEN: process.env.EXPIRES_IN_TIME_FOR_ACCESS_TOKEN,
        EXPIRES_IN_TIME_FOR_REFRESH_TOKEN: process.env.EXPIRES_IN_TIME_FOR_REFRESH_TOKEN,
    }
});