
export default () => ({
    APP:{
        PASSWORD_SALT_ROUNDS: process.env.BCRYPT_HASH_ROUNDS,
        EXPIRES_IN_TIME_FOR_ACCESS_TOKEN_IN_SECONDS: process.env.EXPIRES_IN_TIME_FOR_ACCESS_TOKEN_IN_SECONDS,
        EXPIRES_IN_TIME_FOR_REFRESH_TOKEN_IN_DAYS: process.env.EXPIRES_IN_TIME_FOR_REFRESH_TOKEN_IN_DAYS,
    }
});