version: '3'

services:
  job-creation-service:
    image: node:18.16.0 
    container_name: job-creator
    hostname: job-creation-service
    working_dir: /app
    env_file:
    - ./.env
    ports:
      - "3005:3000" 
    volumes:
      - ./:/app
    command: sh -c "npm install && npm run start:dev"
    depends_on:
      - queue